# Generated by Django 2.2.3 on 2019-07-23 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mclass', models.IntegerField(default=0)),
                ('upperamount', models.IntegerField(default=3)),
                ('nowammount', models.IntegerField(default=0)),
                ('introduction', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybuilt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mclass'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upperamount', models.IntegerField(default=3)),
                ('nowammount', models.IntegerField(default=0)),
                ('introduction', models.CharField(max_length=300)),
                ('formatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchteam', to='snippets.Match')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mybuilt1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['formatch'],
            },
        ),
    ]
